PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS USERS
(
    NAME        TEXT    PRIMARY KEY NOT NULL,
    PASSWORD    CHAR(32)
);

CREATE TABLE IF NOT EXISTS ACCOUNTS
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    DESCR       TEXT                NOT NULL,
    USER_NAME   TEXT                NOT NULL,
    FOREIGN KEY(USER_NAME) REFERENCES USERS(NAME)
);

CREATE TABLE IF NOT EXISTS RECORDS
(
    ID          INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    DESCR       TEXT                NOT NULL,
    AMOUNT      REAL                NOT NULL,
    CATEGORY    TEXT                NOT NULL,
    RECDATE     INTEGER             NOT NULL,
    ACCOUNT_ID  INTEGER             NOT NULL,
    FOREIGN KEY(ACCOUNT_ID) REFERENCES ACCOUNTS(ID),
    FOREIGN KEY(CATEGORY) REFERENCES CATEGORIES(NAME)
);

CREATE TABLE IF NOT EXISTS CATEGORIES
(
    NAME        TEXT PRIMARY KEY NOT NULL
);